### PR TITLE
BEAM allocators can work with any node, not just rabbitmq

### PR DESCRIPTION
**Pull request by deadtrickster**
@gerhard This dashboard now isn't rabbitmq specific plus I tweaked legends. I tried this with my rabbitmq. Could you please confirm this still works for you.
@seriyps could you please try this too.

### CODE REVIEW

**Comment by seriyps** [comment]
Looks great:
screenshot from 2018-05-21 11-08-47

**Comment by deadtrickster** [comment]
@gerhard could you please have a look

**Comment by seriyps** [comment]
Can you, please, upload updated version to grafana.com?

**Comment by gerhard** [comment]
Hi Ilya,

Finally managed to take a look at this. There are a few of things which I think we could do better:

1. Use Erlang node name instead of IP & port. This doesn't couple an Erlang node to an IP or port, which I think makes filtering easier.
2. Don't depend on prometheus_process_collector for RSS memory. Since we've had issues with this deadtrickster/prometheus_process_collector#9, it might make sense to use something else to get RSS memory. I know that you don't want to make this RabbitMQ-specific, I would have suggested `rabbitmq_memory_rss_bytes` otherwise. Speaking of prometheus_process_collector, is there any reason why you've implemented it as a NIF? [Does this help](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/vm_memory_monitor.erl#L284-L290)?

Looks good otherwise! Would be nice if this existed on grafana.com. There are a few more RabbitMQ-specific Grafana/Prometheus dashboards that we will be sharing.

**Comment by deadtrickster** [comment]
Hi, Sergey, Gerhard

I'm on business trip now, will be looking at this next week. 
I think it would be cool to have as many metrics implemented purely in erlang as possibe. There're licensing concerns of course - rabbit is apache2 and prometheus is mit.

Definitely welcome new contributions!

**Comment by deadtrickster** [comment]
new version has been uploaded to grafana.com

**Pull request merged**
