### PR TITLE
Update BEAM-dashboard.json

### PR DESCRIPTION
**Pull request by artukrap**
Migrate graphs from `Phoenix pipeline` dashboard to `BEAM-dashboard`

- https://aldusleaf.org/monitoring-elixir-apps-in-2016-prometheus-and-grafana/
- https://gist.github.com/skosch/415b86ef6a87e3dc102d7f72669bfb1b

### CODE REVIEW

**Comment by deadtrickster** [comment]
Thanks! one thing though - BEAM dashboard is for runtime&process graphs, not application-level. It would be cool to have all-in-one Plugs+Phoenix+Ecto dashboard or maybe just Plugs+Phoenix. Could you please make it into separate dashboard (using Elli as inspiration for http-related graphs)?

**Comment by artukrap** [comment]
@deadtrickster finished the dashboard split. Review new JSON files, when you have time.

**Comment by deadtrickster** [comment]
I added $interval variable and refined phoenix metrics. I also removed new graph from BEAM for now. I don't have ecto app so please test it :-).
I think more metrics say from plugs has to be added and phoenix app could be renamed to Elixir app (to underline its generality). what you think?

**Comment by artukrap** [comment]
Checked both dashboards and everything works fine. 

I agree that elixir app dashboard looks quite small. You think about metrics from https://github.com/deadtrickster/prometheus-plugs ?

**Comment by deadtrickster** [comment]
Yeah, metrics from plugs. Also been thinking about new cowboy2 metrics. Separate dashboard sure, but in this pr probably metrics that complement nicely to plugs, like early errors. Thoughts?

**Comment by artukrap** [comment]
Ye, I agree with you. Will look into `deadtrickster/prometheus-plugs` and check what I could add more.

**Comment by deadtrickster** [comment]
ping :-)

**Comment by artukrap** [comment]
@deadtrickster Sorry for the delay, my bad. Added additional metrics from `prometheus-plugs`

**Comment by deadtrickster** [comment]
Hey, no problem! could you please add a screenshot of the new dashboard?

**Comment by artukrap** [comment]
Update with an image. I guess readme description should be updated after a merge. To set correct image locations.

**Comment by deadtrickster** [comment]
Cool! Thanks :-)

**Pull request merged**
